server:
  port: 1111
eureka:
  instance:
    hostname: discovery
  client:
#    不需要注册本身
    register-with-eureka: false
#    不需要检索服务
    fetch-registry: false

#    service-url: http://${eureka.instance.hostname}:${server.port}/eureka
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
